on:
    push:
        branches:
            - main
    pull_request:    
        branches:
            - main
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Checkout de ramas del codigo
              uses: actions/checkout@v3
            - name: Instalar K6
              run: |
                curl -s https://packagecloud.io/install/repositories/grafana/stable/script.deb.sh | sudo bash
                sudo apt-get install k6
            - name: Ejecucion de las pruebas de carga
              run: k6 run test.js    